gui:
  rows: 4
  filler:
    material: GRAY_STAINED_GLASS_PANE
    name: "&7"
    lore: []
    slots: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]
  bundle-slots: [10, 11, 12, 13, 14, 15, 16, 19, 20, 21, 22, 23, 24, 25]

purchase-button:
  material: EMERALD
  name: "&aPurchase Bundle"
  lore:
    - "&7Price: &6%price% &7credits"
    - "&7Time Left: &e%timeleft%"
    - "&7Click to buy!"

confirm-menu:
  title: "&cConfirm Purchase?"
  confirm-item:
    material: GREEN_WOOL
    name: "&aConfirm"
  cancel-item:
    material: RED_WOOL
    name: "&cCancel"
