name: BundlePlugin
main: me.minimize.bundleplugin.BundlePlugin
version: 1.0
author: minimize
api-version: 1.20

commands:
  bundles:
    description: Opens the bundle shop
    usage: /bundles
    permission: "bundleplugin.use"
    permission-message: "&cYou lack permission."

permissions:
  bundleplugin.use:
    default: true
  bundleplugin.reload:
    default: op
